// <auto-generated />
using System;
using BedBrigade.Data;
using BedBrigade.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BedBrigade.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230909083330_CreateVolunteerEvents")]
    partial class CreateVolunteerEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BedBrigade.Data.Models.VolunteerEvents", b =>
                {
                    // identification fields

                    b.Property<int>("RegistrationId")
                       .ValueGeneratedOnAdd()
                       .HasColumnType("int");
                        SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistrationId"));
                   
                    b.Property<int>("LocationId")
                         .IsRequired()
                         .HasColumnType("int");

                    b.Property<int>("ScheduleId")
                      .IsRequired()
                      .HasColumnType("int");

                    b.Property<int>("VolunteerId")
                      .IsRequired()
                      .HasColumnType("int");

                    // Description Fields

                  
                    b.Property<string>("VolunteerEventNote")
                     .HasMaxLength(4000)
                     .HasColumnType("nvarchar(4000)");                                      

                    // System Fields

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MachineName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MachineName")
                     .HasMaxLength(100)
                     .HasColumnType("nvarchar(100)");

                    b.HasKey("RegistrationId");

                    b.ToTable("VolunteerEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
