--This deletes all tables in the database
drop table if exists EmailQueue
drop table if exists SmsQueue
drop table if exists BedRequests
drop table if exists Configurations
drop table if exists ContactUs
drop table if exists Content
drop table if exists ContentHistory
drop table if exists DonationCampaigns
drop table if exists Donations
drop table if exists GeoLocationQueue
drop table if exists Media
drop table if exists Roles
drop table if exists Templates
drop table if exists UserPersist
drop table if exists Users
drop table if exists SignUps
drop table if exists Volunteers
drop table if exists VolunteersFor
drop table if exists Translations
drop table if exists ContentTranslations
drop table if exists ContentTranslationQueue
drop table if exists TranslationQueue
drop table if exists SpokenLanguages
drop table if exists Subscriptions
drop table if exists Newsletters
drop table if exists Schedules
drop table if exists Locations
drop table if exists MetroAreas
drop table if exists __EFMigrationsHistory
